---
title: "Data Cleaning"
author: "Michael Larbie, Sarah Piper, Nikhita Gopisetty"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import libraries}
library(dplyr)
library(tidyverse)
library(caret)
```
```{r import data}
raw_data <- read_csv('data/adult21.csv')
```
```{r select columns}
data_select <- raw_data %>%
  dplyr::select(REGION, SEX_A, CVDDIAG_A, NATUSBORN_A, RACEALLP_A, MEDNG12M_A,
         PAYWORRY_A, DIBEV_A, ASEV_A, CHLEV_A, HYPEV_A, MEDRXTRT_A,
         HLTHCOND_A, DEPEV_A) %>% 
  filter(SEX_A == 1 | SEX_A == 2,
         CVDDIAG_A == 1 | CVDDIAG_A == 2, 
         NATUSBORN_A == 1 | NATUSBORN_A == 2,
         RACEALLP_A == 1 | RACEALLP_A == 2 | RACEALLP_A == 3 | RACEALLP_A == 8,
         MEDNG12M_A ==1 | MEDNG12M_A == 2,
         PAYWORRY_A == 1 | PAYWORRY_A == 2 | PAYWORRY_A == 3,
         DIBEV_A == 1 | DIBEV_A == 2,
         ASEV_A == 1 | ASEV_A == 2, 
         CHLEV_A == 1 | CHLEV_A == 2, 
         HYPEV_A == 1 | HYPEV_A == 2,
         MEDRXTRT_A == 1 | MEDRXTRT_A == 2,
         HLTHCOND_A == 1 | HLTHCOND_A == 2,
         DEPEV_A == 1 | DEPEV_A == 2)
```

```{r drop na}
data <- drop_na(data_select)
str(data)
```

```{r split data}
data_split <- createDataPartition(data$CVDDIAG_A, p = 0.8, list = FALSE)
data_train <- data[data_split,]
data_test <- data[-data_split,]
dim(data_train)
dim(data_test)
```

```{r factor}
data_train$NATUSBORN_A <- as.factor(data_train$NATUSBORN_A)
data_train$SEX_A <- as.factor(data_train$NATUSBORN_A)
data_train$CVDDIAG_A <- as.factor(data_train$CVDDIAG_A)
data_train$REGION <- as.factor(data_train$REGION)
data_train$HYPEV_A <- as.factor(data_train$HYPEV_A)
data_train$CHLEV_A <- as.factor(data_train$CHLEV_A)
data_train$ASEV_A <- as.factor(data_train$ASEV_A)
data_train$DIBEV_A <- as.factor(data_train$DIBEV_A)
data_train$MEDNG12M_A <- as.factor(data_train$MEDNG12M_A)
data_train$PAYWORRY_A <- as.factor(data_train$PAYWORRY_A)
data_train$RACEALLP_A <- as.factor(data_train$RACEALLP_A)
data_train$MEDRXTRT_A <- as.factor(data_train$MEDRXTRT_A)
data_train$HLTHCOND_A <- as.factor(data_train$HLTHCOND_A)
data_train$DEPEV_A <- as.factor(data_train$DEPEV_A)
str(data_train)
```

```{r factor}
data_test$NATUSBORN_A <- as.factor(data_test$NATUSBORN_A)
data_test$SEX_A <- as.factor(data_test$NATUSBORN_A)
data_test$CVDDIAG_A <- as.factor(data_test$CVDDIAG_A)
data_test$REGION <- as.factor(data_test$REGION)
data_test$HYPEV_A <- as.factor(data_test$HYPEV_A)
data_test$CHLEV_A <- as.factor(data_test$CHLEV_A)
data_test$ASEV_A <- as.factor(data_test$ASEV_A)
data_test$DIBEV_A <- as.factor(data_test$DIBEV_A)
data_test$MEDNG12M_A <- as.factor(data_test$MEDNG12M_A)
data_test$PAYWORRY_A <- as.factor(data_test$PAYWORRY_A)
data_test$RACEALLP_A <- as.factor(data_test$RACEALLP_A)
data_test$MEDRXTRT_A <- as.factor(data_test$MEDRXTRT_A)
data_test$HLTHCOND_A <- as.factor(data_test$HLTHCOND_A)
data_test$DEPEV_A <- as.factor(data_test$DEPEV_A)
str(data_test)
```

```{r export data}
write.csv(data_train, 'training_data.csv')
write.csv(data_test, 'testing_data.csv')
```

