---
title: "Exploratory Data Analysis"
author: "Michael Larbie, Sarah Piper, Nikhita Gopisetty"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

##Import Packagaes
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(viridis)
library(ggpubr)
```

## Load Data
```{r}
data <- read_csv('data/adult21.csv')
```

## Native Born Compared to Non-Native Born Covid Diagnosis
```{r}
data$NATUSBORN_A <- as.factor(data$NATUSBORN_A)
data$CVDDIAG_A <- as.factor(data$CVDDIAG_A)

data %>% count(NATUSBORN_A,CVDDIAG_A) %>%
ggplot(aes(fill = CVDDIAG_A, x = NATUSBORN_A, y =n)) +
geom_bar(position = "fill", stat = "identity") + 
  labs(title = "Native v Non-Native Born", x = "Origin of Birth",
                  y = "Number of Respondents")
```

## Region Positive Covid Diagnosis
```{r}
data$REGION <- as.factor(data$REGION)


data %>% count(REGION,CVDDIAG_A) %>% 
  ggplot(aes(fill = REGION, x = CVDDIAG_A, y = n)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Region Positive Covid Diagnosis", x = "Covid Diagnosis",
       y = "Number of Respondents")

data %>% count(NATUSBORN_A,REGION) %>% 
  ggplot(aes(fill = NATUSBORN_A, x = REGION, y = n)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Regional Nativity Status", x = "Region",
       y = "Number of Respondents")
```

## Diseases and Covid Diagnosis
```{r}
data$HYPEV_A <- as.factor(data$HYPEV_A)
data$CHLEV_A <- as.factor(data$CHLEV_A)
data$ASEV_A <- as.factor(data$ASEV_A)
data$DIBEV_A <- as.factor(data$DIBEV_A)

hypertension <- data %>% count(HYPEV_A,CVDDIAG_A) %>% 
  ggplot(aes(fill = CVDDIAG_A, x = HYPEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Hypertension and Covid Diagnosis", x = "Hypertension",
       y = "Number of Respondents")

nhypertension <- data %>% count(HYPEV_A,NATUSBORN_A) %>% 
  ggplot(aes(fill = NATUSBORN_A, x = HYPEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Hypertension and Nativity", x = "Hypertension",
       y = "Number of Respondents")

cholesterol <- data %>% count(CHLEV_A,CVDDIAG_A) %>% 
  ggplot(aes(fill = CVDDIAG_A, x = CHLEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Cholesterol and Covid Diagnosis", x = "Cholesterol",
       y = "Number of Respondents")

ncholesterol <- data %>% count(CHLEV_A,NATUSBORN_A) %>% 
  ggplot(aes(fill = NATUSBORN_A, x = CHLEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Cholesterol and Nativity", x = "Cholesterol",
       y = "Number of Respondents")

asthma <- data %>% count(ASEV_A,CVDDIAG_A) %>% 
  ggplot(aes(fill = CVDDIAG_A, x = ASEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Asthma and Covid Diagnosis", x = "Asthma",
       y = "Number of Respondents")

nasthma <- data %>% count(ASEV_A,NATUSBORN_A) %>% 
  ggplot(aes(fill = NATUSBORN_A, x = ASEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Asthma and Covid Diagnosis", x = "Asthma",
       y = "Number of Respondents") 

diabetes <- data %>% count(DIBEV_A,CVDDIAG_A) %>% 
  ggplot(aes(fill = CVDDIAG_A, x = DIBEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Diabetes and Covid Diagnosis", x = "Diabetes",
       y = "Number of Respondents")


ndiabetes <- data %>% count(DIBEV_A,NATUSBORN_A) %>% 
  ggplot(aes(fill = NATUSBORN_A, x = DIBEV_A, y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Diabetes and Covid Diagnosis", x = "Diabetes",
       y = "Number of Respondents")

ggarrange(hypertension, cholesterol, asthma, diabetes, nrow = 2, ncol = 2 )
ggarrange(nhypertension, ncholesterol, nasthma, ndiabetes, nrow = 2, ncol = 2 )
```

## Social Determinants and Covid Diagnosis
```{r}
data$MEDNG12M_A <- as.factor(data$MEDNG12M_A)
data$PAYWORRY_A <- as.factor(data$PAYWORRY_A)
data$FDSRUNOUT_A <- as.factor(data$FDSRUNOUT_A)

data %>% count(MEDNG12M_A,CVDDIAG_A) %>% 
ggplot(aes(fill = CVDDIAG_A, x = MEDNG12M_A, y = n)) +
geom_bar(position = "stack", stat = "identity") +
labs(title = "Access to Care and Covid Diagnosis", x = "Access to Care",
       y = "Number of Respondents")

data %>% count(PAYWORRY_A,CVDDIAG_A) %>% 
ggplot(aes(fill = CVDDIAG_A, x = PAYWORRY_A, y = n)) +
geom_bar(position = "stack", stat = "identity") +
labs(title = "Ability to Pay for Healthcare and Covid Diagnosis", x = "Paying for Healthcare",
       y = "Number of Respondents")

data %>% count(FDSRUNOUT_A,CVDDIAG_A) %>% 
ggplot(aes(fill = CVDDIAG_A, x = FDSRUNOUT_A, y = n)) +
geom_bar(position = "stack", stat = "identity") +
labs(title = "Food Security and Covid Diagnosis", x = "Food Security",
       y = "Number of Respondents")
```

## Race and Covid Diagnois
```{r}
data$RACEALLP_A <- as.factor(data$RACEALLP_A)

data %>% mutate(race = case_when(RACEALLP_A == 1 ~ "White",
                                RACEALLP_A == 2 ~ "Black",
                                RACEALLP_A == 3 ~ "Asian",
                                RACEALLP_A == 8 ~ "Latino")) %>% 
mutate(immigrant = case_when(NATUSBORN_A == 1 ~ "Native",
                                NATUSBORN_A == 2 ~ "Immigrant"))%>%
mutate(covid = case_when(CVDDIAG_A == 1 ~ "Positive",
                             CVDDIAG_A == 2 ~ "Negative")) %>%
drop_na(race, immigrant, covid) %>%
count(race, immigrant, covid) %>%
ggplot(aes(fill = covid, x = race, y = n)) +
geom_bar(position = "fill", stat = "identity") +
facet_wrap(~ immigrant)+
labs(title = "Relationship Between Race, Immigration and Covid Diagnosis", 
     x = "Race",
     y = "Fraction of Respondents")
```

## Sex and Covid Diagnosis
```{r}
data$SEX_A <- as.factor(data$SEX_A)

data %>% count(SEX_A,CVDDIAG_A) %>% 
ggplot(aes(fill = SEX_A, x = CVDDIAG_A, y = n)) +
geom_bar(position = "dodge", stat = "identity") +
labs(title = "Race and Covid Diagnosis", x = "Covid Diagnosis",
       y = "Number of Respondents")
```

